#cloud-config
runcmd:
  - sudo yum update -y
  - sudo amazon-linux-extras install docker
  - sudo service docker start
  - sudo systemctl enable docker
  - sudo usermod -a -G docker ec2-user
  - docker pull jonaswinkler/paperless-ng:${paperless_image_tag}
  - docker run -e PAPERLESS_REDIS=${paperless_redis} -e PAPERLESS_DBHOST=${paperless_dbhost} -e PAPERLESS_DBUSER=${paperless_dbuser} -e PAPERLESS_DBPASS=${paperless_dbpassword} -e PAPERLESS_SECRET_KEY="${paperless_secret_key}" -p 8000:8000 --name paperless jonaswinkler/paperless-ng
